# This is a basic workflow to help you get started with Actions

name: Flutter Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  FLUTTER_VERSION: "2.10.1"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Flutter
        run: git clone https://github.com/flutter/flutter.git --depth 1 -b $FLUTTER_VERSION flutter
      - name: Add Flutter to Path
        run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
      - name: Install Dependencies
        run: flutter pub get
      #- name: Flutter Analyze
      #  run: flutter analyze --no-pub
      - name: Check Flutter Formatting
        run: flutter format lib/** --set-exit-if-changed
      - name: Run Flutter Tests
        run: flutter test --no-pub
